name = "Monument"
license = "MIT"
licenselink = "https://github.com/MrCroxx/Hugo-Theme-Monument/blob/master/LICENSE"
description = "A colorful Hugo theme with various out-of-box features."
homepage = "http://hugo-theme-monument.github.io/"
tags = ['blog']
features = ['Timeline','Katex','Gitalk','ChartJS','HighlightJS']
min_version = "0.41"

[author]
  name = "Croxx"
  homepage = "mrcroxx.github.io"